// ══════════════════════════════════════════════
//  Quallis — Vercel Build Config Generator
//  Generates js/config.js from environment variables during Vercel build
// ══════════════════════════════════════════════

const fs = require("fs");
const path = require("path");

const supabaseUrl = process.env.SUPABASE_URL || "";
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || "";
const geminiApiKey = process.env.GEMINI_API_KEY || "";

const configContent = `// Auto-generated by generate-config.js during build
const CONFIG = {
  SUPABASE_URL:      "${supabaseUrl}",
  SUPABASE_ANON_KEY: "${supabaseAnonKey}",
  GEMINI_API_KEY:    "${geminiApiKey}",
  GEMINI_MODEL:      "gemini-3.6-flash",
  TABLE_FARMERS:     "farmers",
};
Object.freeze(CONFIG);
`;

const jsDir = path.join(__dirname, "js");
if (!fs.existsSync(jsDir)) {
  fs.mkdirSync(jsDir, { recursive: true });
}

fs.writeFileSync(path.join(jsDir, "config.js"), configContent);
console.log("✅ Successfully generated js/config.js from environment variables.");
